# Project Configuration
project_name: "my-data-science-project"
version: "1.0.0"
author: "Your Name"

# Data Configuration
data:
  raw_path: "data/raw/"
  interim_path: "data/interim/"
  processed_path: "data/processed/"
  
# Model Configuration
model:
  type: "random_forest"
  random_state: 42
  test_size: 0.2
  
# Feature Engineering
features:
  target_column: "target"
  categorical_features: []
  numerical_features: []
  
# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"